### ISSUE TITLE
kanban board setup

### ISSUE THREAD

**Issue by ashmalzahra** [ashmalzahra/space-travelers-hub#65]
[React Group Project](https://github.com/ashmalzahra/space-travelers-hub/projects/2)
_We are a group of two._

**Comment by topeogunleye** [comment]
Hi @ashmalzahra, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![dwayne-the-rock](https://user-images.githubusercontent.com/52934128/180645370-67438f1f-e27d-4f8b-88d6-1e3474394f0a.gif)

## (Highlights) Good Points: 💪 
- The board is set 👍
- The PR title and description looks professional, with all the information 👍

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

You can also consider:
- Nothing to mention.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @topeogunleye in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
